#!/bin/sh
echo 'Installing initial dependencies...'
apt update
apt install tor openjdk-8-jre firefox-esr

# install geckodriver
echo 'Installing geckodriver...'
wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
sh -c 'tar -x geckodriver -zf geckodriver-v0.24.0-linux64.tar.gz -O > /usr/bin/geckodriver'
chmod +x /usr/bin/geckodriver
rm geckodriver-v0.24.0-linux64.tar.gz
echo 'Dependency installation complete.'